---
title: "Data Comp"
---

### Introduction

Analysing customer data.

### [About Data]

#### About age column
- 1 = 10 ~ 19
- 2 = 20 ~ 24
- 3 = 25 ~ 29
- 4 = 30 ~ 34
- 5 = 35 ~ 39
- 6 = 40 ~

#### About gender column
  
- 1 = male
- 2 = female


#### About prefrectures column

01 ????????? 02 ????????? 03 ????????? 04 ????????? 05 ????????? 
06 ????????? 07 ????????? 08 ????????? 09 ????????? 10 ????????? 
11 ????????? 12 ????????? 13 ????????? 14 ???????????? 15 ????????? 
16 ????????? 17 ????????? 18 ????????? 19 ????????? 20 ????????? 
21 ????????? 22 ????????? 23 ????????? 24 ????????? 25 ????????? 
26 ????????? 27 ????????? 28 ????????? 29 ????????? 30 ???????????? 
31 ????????? 32 ????????? 33 ????????? 34 ????????? 35 ????????? 
36 ????????? 37 ????????? 38 ????????? 39 ????????? 40 ????????? 
41 ????????? 42 ????????? 43 ????????? 44 ????????? 45 ????????? 
46 ???????????? 47 ??????

### [Start Analyzing]

#### Importing member.csv
```{r}
library(ggplot2)
member <- read.csv("~/Developer/dataComp/DataComp/Kazushi/data/member.csv", header = TRUE)
```

#### Creating a Pie chart of gender ratio
```{r}
genderRatio <- table(member$gender == 1)
genderHeader <- c(
  paste("(female)", genderRatio[1]),
  paste("(male)", genderRatio[2])
)
names(genderRatio) <- genderHeader
pie(genderRatio, col = rainbow(2))
```


#### Creating a Pie chart and a bar plot of age ratio

```{r}
ages <- member$age
agesRatio <- c(
  table(ages == 1)[2],
  table(ages == 2)[2],
  table(ages == 3)[2],
  table(ages == 4)[2],
  table(ages == 5)[2],
  table(ages == 6)[2]
)

agesHeader <- c(
  paste("(10 ~ 19)"),
  paste("(20 ~ 24)"),
  paste("(25 ~ 30)"),
  paste("(30 ~ 34)"),
  paste("(35 ~ 40)"),
  paste("(40 ~ )")
)
names(agesRatio) <- agesHeader

par(mfrow=c(1, 2))
pie(agesRatio, col = rainbow(20))
plot(agesRatio, col = rainbow(20))
```

#### Creating Stacked Bar Blot about Age and Gender

```{r}
malesByAge <- c()
femalesByAge <- c()
for(i in 1:6) {
  byAge <- member[member$age == i,]
  
  count <- length(byAge[byAge$gender == 1,][,1])
  malesByAge <- rbind(malesByAge, count)
  
  count <- length(byAge[byAge$gender == 2,][,1])
  femalesByAge <- rbind(femalesByAge, count)
}

data <- c()
data <- rbind(data, malesByAge[,1])
data <- rbind(data, femalesByAge[,1])

colnames(data) = 1:6

par(mfrow=c(1, 1))

barplot(
  as.matrix(data),
  col=rainbow(10),
  main="Stacked Bar Plot",
  legend.text = c("Male", "Female")
)
```


#### Creating bar plot of prefectures

```{r}
data <- c()
pref <- member$prefectures
for(i in 1:47) {
  count <- sum(pref == i)
  data <- cbind(data, count)
}

colnames(data) = 1:47

barplot(
  data,
  main = "Prefecture Distribution",
  xlab = "Prefecture Code",
  ylab = "Number of people"
)

```


