---
output:
  pdf_document: default
  html_document: default
---

# クラスタ ex: P(クラスタ1)
```{r}
getProbByCluster <- function(file) {
  topics <- read.csv(file, header = FALSE)
  
  clusterCount <- ncol(topics)
  result <- c()
  
  # Get mean of each cluster
  for (i in 1:clusterCount) {
    result <- c(result, mean(topics[,i]))
  }
  
  return(result)
}

file <- './data/topicdist/topicdist_11.txt'
print(getProbByCluster(file))
```

# 確率 ex: P(男)

```{r}
getProbFromMember <- function(key, value) {
  file <- './data/member_analyzed.csv'
  members <- read.csv(file,header=TRUE)
  
  # 条件の行数を取得する
  count <- table(members[key] == value)[2]
  
  prob <- count / nrow(members)
  names(prob) <- NULL
  
  return(prob)
}

print(getProbFromMember('sex', 1))
print(getProbFromMember('prefectures', 17))
print(getProbFromMember('age', 2))
```

# ex: P(クラスタ1 | 男)
```{r}
# 関数名がクソ
getProbForMemberByCluster <- function(key, value, topicFile, file) {
  # file <- './data/member_analyzed.csv'
  members <- read.csv(file, header=TRUE)
  tmp <- members[key] == value
 
  topics <- read.csv(topicFile, header=TRUE)
  res <- c()
  
  ## for each clusters
  for(clusIndex in 1:ncol(topics)) {
    clusRes <- c()
    
    ## for each members
    for(i in 1:nrow(topics)) {
      if(tmp[i] == TRUE) {
        # only check cluster 1
        clusRes <- c(clusRes, topics[i, clusIndex])
      }
    }
    
    res <- c(res, mean(clusRes))
      
  }
  
  return(res)
}

memberFile <- './data/member_analyzed.csv'
file <- './data/topicdist/topicdist_11.txt'
print(getProbForMemberByCluster('age', 2, file, memberFile))
```

# 合わせ技

```{r}
# 関数名がクソ

getResult <- function(topicDistFile, memberFile, key, value, saveDist = "~/") {
  library(ggplot2)
  # P(男)
  var1 <- getProbFromMember(key, value)
  # P(クラスタ|男)
  var2 <- getProbForMemberByCluster(key, value, topicDistFile, memberFile)
  # P(クラスタ)
  var3  <-getProbByCluster(topicDistFile)
  
  result <- c()
  
  numOfCluters = length(var2)
  
  for(i in 1:numOfCluters) {
    
    r <- (var2[i] * var1) / var3[i]
    
    result <- c(result, r)
  }
  
  # save the graph
  df = data.frame(result)
  graph <- ggplot(data.frame(result), aes(seq_along(result), result)) 
  graph <- graph + ggtitle(paste(key, value))
  graph <- graph + geom_bar(stat="identity")
  graph <- graph + theme(plot.title = element_text(lineheight=.8, face="bold")) + ylim(0,1)
  file <- paste(saveDist, key, "_", value,".png",sep="")
  ggsave(file=file)
  
  return(result)
}

memberFile <- './data/member_analyzed.csv'
topicsDistFile = '~/Developer/DataComp/Yagi/ttm/log/log_2016-11-26-18/log_2016-11-26-18_K5_P12_I100/topicdist/topicdist_11.txt'

result <- getResult(topicsDistFile, memberFile, 'sex', 1)
result <- getResult(topicsDistFile, memberFile, 'sex', 2)

for(i in 1:47) {
  getResult(topicsDistFile, memberFile, 'prefectures', i)
}

```









